# Generated by Django 3.0.7 on 2020-10-09 10:49

from django.db import migrations, models


def calculate_cost(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.all()
    for order_item in order_items:
        order_item.cost = order_item.quantity * order_item.product.price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0033_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.RunPython(calculate_cost)
    ]
