# Generated by Django 3.0.7 on 2020-10-09 15:46

from django.db import migrations, models


def set_status(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    orders = Order.objects.all()
    for order in orders:
        order.status = 'In progress'
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0034_orderitem_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Done', 'Выполнен'), ('In progress', 'В работе')], default='In progress', max_length=11, verbose_name='Статус'),
        ),
        migrations.RunPython(set_status)
    ]
