# Generated by Django 3.0.7 on 2020-10-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0035_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Плюнуть в бургер', verbose_name='Комментарий'),
        ),
    ]
