# Generated by Django 3.2 on 2021-05-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
        ('foodcartapp', '0042_auto_20210519_1913'),
    ]

    operations = [
    ]
